schema_version: '1.0'
mcp_name: 'Irish Law MCP'
jurisdiction: 'IE'

sources:
  - name: 'eISB'
    authority: 'Office of the Attorney General'
    official_portal: 'https://www.irishstatutebook.ie'
    canonical_identifier: 'Short title + year (e.g., "Data Protection Act 2018")'
    retrieval_method: 'HTML_SCRAPE'
    api_documentation: 'https://www.irishstatutebook.ie/eli/'
    update_frequency: 'monthly'
    last_ingested: '2026-02-16'
    license_or_terms:
      type: 'Government open data'
      url: 'https://www.irishstatutebook.ie/eli/'
      summary: 'Irish government open data with ELI URIs'
    coverage:
      scope: 'Irish Acts and Statutory Instruments (cybersecurity and data protection scope)'
      limitations: 'Initial release covers key cybersecurity legislation only'
    languages:
      - 'en'

data_freshness:
  automated_checks: true
  check_frequency: 'monthly'
  last_verified: '2026-02-16'
